[build]
publish = "src/landing-page"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/css/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"